---
- name: stop and remove consul ,sl ,nginx ,cl and activemq containers
  docker_container:
    name: "{{item}}"
    state: absent
  with_items:
  - sl
  - nginx-sl
  - consul
  - cl
  - activemq
  - configuration
  - db-manager


