---
- name: remove {{primehome_home}}
  file: path={{primehome_home}} state=absent
  when:
   - "{{primehome_remove_mount}} == true"

- name: remove {{primehome_home}}/vault/vault_token
  file: path={{primehome_home}}/vault state=absent


- name: create "{{primehome_home}}/var/log"
  file: path="{{primehome_home}}/var/log" state=directory

- name: remove
  shell: docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)


#- name: stop and remove consul ,sl ,nginx ,cl and activemq containers
#  docker_container:
#    name: "{{item}}" 
#    state: absent
#  with_items:
#  - sl
#  - nginx-sl
#  - consul
#  - cl
#  - activemq
#  - configuration
#  - db-manager

- name: creating consul container
  docker_container:
    name: consul
    image: dockerhub.cisco.com/primehome-v2-docker/consul:b{{primehome_build}}
    state: started
    pull: true
    volumes:
    - "{{primehome_home}}/vault:/var/consul/vault/"
    - "{{primehome_home}}/central-config:/var/primehome_in"
    network_mode: host
    env:
     CONSUL_ARGS: "--datacenter=dc1 -server -bootstrap"
     CONSUL_ADVERTISE_ADDR: "{{hostvars[inventory_hostname]['ansible_' + consul_nic]['ipv4']['address']}}"
     CONSUL_DNS_PORT: 8610
     CONSUL_ADDR: "{hostvars[inventory_hostname]['ansible_' + consul_nic]['ipv4']['address']}}"
    capabilities:
    - IPC_LOCK

- pause:
   seconds: 20

- name: fetch consul key 
  command: docker exec  consul cat /var/consul/vault/vault_token
  register: vault_token
- debug: msg={{vault_token.stdout}}
#- name: setting consul key to file system
#  command: "echo {{vault_token.stdout}} > {{primehome_home}}vault_token"


- name: creating deploy container
  docker_container:
    name: deploy
    image: dockerhub.cisco.com/primehome-v2-docker/configuration-{{primehome_customer}}:b{{primehome_build}}
    state: started
    pull: true
    volumes:
    - "{{primehome_home}}:/deploy"
    command: "common autodeploy liquibase"
  run_once: true
  delegate_to: "{{play_hosts[0]}}"


- name: creating db-manager container
  docker_container:
    name: db-manager
    image: dockerhub.cisco.com/primehome-v2-docker/db-manager:b{{primehome_build}}
    state: started
    pull: true
    volumes:
    - "{{primehome_home}}/liquibase:/liquibase_folder"
    - "{{primehome_home}}/liquibase/logs:/logs_volume"
    network_mode: host
    env:
     LOG_LEVEL: "info"
     CONSUL_IP: "{{hostvars[inventory_hostname]['ansible_' + consul_nic]['ipv4']['address']}}"
     CUSTOMER: "{{primehome_customer}}"
     MODE: "PROD"
     TOKEN: "{{vault_token.stdout}}"
     SILENT_MODE: "true"
     COMMAND: "upgrade"
  run_once: true
  delegate_to: "{{play_hosts[0]}}"


- name: activemq container
  docker_container:
    name: activemq
    image: dockerhub.cisco.com/primehome-v2-docker/activemq:b{{primehome_build}}
    state: started
    pull: true
    volumes:
    - "{{primehome_home}}/vault:/root/vault"
    network_mode: host
    env:
     CONSUL_DNS_PORT: 8621
     CONSUL_ADDR: "{{hostvars[inventory_hostname]['ansible_' + consul_nic]['ipv4']['address']}}"
     CONSUL_HTTP_PORT: 8511


- name: creating sl container
  docker_container:
    name: sl
    image: dockerhub.cisco.com/primehome-v2-docker/sl:b{{primehome_build}}
    state: started
    pull: true
    volumes:
    - "{{primehome_home}}/vault:/root/vault"
    - "{{primehome_home}}/autodeploy:/opt/primehome/autodeploy"
    - "{{primehome_home}}/ActiveCustomer:/opt/primehome/ActiveCustomer"
    - "{{primehome_home}}/var/log:/opt/primehome/var/log"
    - "{{primehome_home}}/var/log:/opt/primehome/portal/tomcat/logs"   
    network_mode: host
    env:
     CONSUL_DNS_PORT: 8620
     CONSUL_ADDR: "{{hostvars[inventory_hostname]['ansible_' + consul_nic]['ipv4']['address']}}"
     CONSUL_HTTP_PORT: 8510

- name: creating sl-nginx container
  docker_container:
    name: "nginx-sl"
    image: dockerhub.cisco.com/primehome-v2-docker/nginx-sl:b{{primehome_build}}
    state: started
    pull: true
    volumes:
    - "{{primehome_home}}/vault:/root/vault"
    network_mode: host
    env:
     CONSUL_DNS_PORT: 8630
     CONSUL_ADDR: "{{hostvars[inventory_hostname]['ansible_' + consul_nic]['ipv4']['address']}}"
     CONFIG_PATHS: "nginx-sl"
     CONSUL_HTTP_PORT: 8520
     CONSUL_ARGS: "-node={{inventory_hostname}}-nginx-sl"

- name: creating cl container
  docker_container:
    name: "cl"
    image: dockerhub.cisco.com/primehome-v2-docker/cl:b{{primehome_build}}
    state: started
    pull: true
    volumes:
    - "{{primehome_home}}/vault:/root/vault"
    - "{{primehome_home}}/ActiveCustomer:/opt/primehome/ActiveCustomer"
    - "{{primehome_home}}/var/log:/opt/primehome/var/log"
    - "{{primehome_home}}/var/log:/opt/primehome/acs/logs"
 
    network_mode: host
    env:
     CONSUL_DNS_PORT: 8641
     CONSUL_ADDR: "{{hostvars[inventory_hostname]['ansible_' + consul_nic]['ipv4']['address']}}"
     CONSUL_HTTP_PORT: 8531


- name: creating cl-nginx container
  docker_container:
    name: "nginx-cl"
    image: dockerhub.cisco.com/primehome-v2-docker/nginx-cl:b{{primehome_build}}
    state: started
    pull: true
    volumes:
    - "{{primehome_home}}/vault:/root/vault"

    network_mode: host
    env:
     CONSUL_DNS_PORT: 8651
     CONSUL_ADDR: "{{hostvars[inventory_hostname]['ansible_' + consul_nic]['ipv4']['address']}}"
     CONSUL_HTTP_PORT: 8541






